# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/MyCollection" -apiKey=${KATALON_API_KEY}
          environment:
            LANG: ja_JP.UTF-8 
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
