# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.12
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test
            Suites/TS_RegressionTest'
